# - this module looks for genlib
# Defines:
#   GENLIB_LIBRARIES
#   GENLIB_FOUND
#   GENLIB_VERSION
#   GENLIB_MAJOR_VERSION
#   GENLIB_MINOR_VERSION

find_package(PackageHandleStandardArgs)

find_library(GENLIB_LIBRARIES gens HINTS $ENV{HOME}/lib/)

get_filename_component(GENLIB_REAL_PATH ${GENLIB_LIBRARIES} REALPATH)

string(REGEX MATCH "[0-9]+" GENLIB_MAJOR_VERSION ${GENLIB_REAL_PATH})
string(REGEX MATCH "[0-9]+.[0-9]+$" GENLIB_MINOR_VERSION ${GENLIB_REAL_PATH})

set(GENLIB_VERSION ${GENLIB_MAJOR_VERSION}.${GENLIB_MINOR_VERSION})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(genlib
        REQUIRED_VARS GENLIB_LIBRARIES
        VERSION_VAR GENLIB_VERSION)

MARK_AS_ADVANCED (
        GENLIB_LIBRARIES
        GENLIB_VERSION
        GENLIB_MAJOR_VERSION
        GENLIB_MINOR_VERSION
)